[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'develop']
  renderJavaScript = true

[functions]
  [functions."collectCarbon"]
    external_node_modules = ["jsdom"]
    schedule = "0,15,30,45 * * * *"
