[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_CONTENTFUL_ENVIRONMENT = "master"

[context.branch-deploy.environment]
  REACT_APP_CONTENTFUL_ENVIRONMENT = "2022-11-09-Missy" # Update to new working env

[context.deploy-preview.environment]
  REACT_APP_CONTENTFUL_ENVIRONMENT = "2022-11-09-Missy" # Update to new working env

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['master', 'develop']
  renderJavaScript = true
