[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'develop']
  renderJavaScript = true

[functions]
  external_node_modules = ["jsdom"]
  [functions."carbon"]
    schedule = "0 0 * * 1"
