[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['master', 'develop']
  renderJavaScript = true

[build]
  publish = "docs/build"
  command = "npm run build:docs"